// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package sqlc

import (
	"database/sql"
)

type AdminDivision struct {
	DivisionID   int32  `json:"division_id"`
	DivisionName string `json:"division_name"`
}

type AdminStatus struct {
	AdminStatusID int32          `json:"admin_status_id"`
	AdminStatus   sql.NullString `json:"admin_status"`
}
